name: classified
description: A new Flutter project.
publish_to: 'none'
version: 0.1.3+4

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  google_sign_in: ^6.1.0
  image_picker: ^0.8.7+4
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500  
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700    
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 900   
    - family: Opensans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 900
             